#define LCD_RS_PIN GPIO_NUM_25
//#define LCD_RW_PIN GPIO_NUM_?
#define LCD_EN_PIN GPIO_NUM_26
#define LCD_D4_PIN GPIO_NUM_27
#define LCD_D5_PIN GPIO_NUM_14
#define LCD_D6_PIN GPIO_NUM_22
#define LCD_D7_PIN GPIO_NUM_13